#!/bin/bash

# customize loading the fpga design (.openocd) with BEFORE and AFTER steps as needed,
# as well as being able to directly run the loading process from OpenOCD itself rather
# than using another interface such as telnet/gdb
# REQ:
# 1. OpenOCD probe is connected to EOS_S3 and it is in DEBUG mode
# 2. openocd is available in the path ('source debugenvsetup.sh')
# 3. (.openocd) has been generated by adding a 'openocd' to the -dump command to ql_symbiflow

OPENOCD_PATH=$(which openocd)
OPENOCD_INTERACE_CFG="interface/jlink_swd.cfg"

################################################################################
#   getopt based parsing
################################################################################
# option strings
SHORT="" # no short options at all, clearer that way.
# reference on how to enforce no short options: https://unix.stackexchange.com/questions/162624/how-to-use-getopt-in-bash-command-line-with-only-long-options
LONG="openocd-path:,openocd-if-cfg:,help"


# read the options
OPTS=$(getopt --options "$SHORT" --long "$LONG" --name "$0" -- "$@")

if [ $? != 0 ] ; then echo "ERROR: failed to parse options...exiting." >&2 ; exit 1 ; fi

eval set -- "$OPTS"

usage()
{
    printf "\n"
    printf "[%s] usage:\n" $(basename $0)
    printf "\n"
    printf "build the fpga design\n"
    printf "\n"
    printf " syntax: $0 --openocd-path=/path/to/openocd --openocd-if-cfg=/path/to/probe/cfg\n"
    printf "\n"
    printf "example: $0 --openocd-path=/usr/bin/openocd --openocd-if-cfg=interface/ft2232h_swd.cfg\n"
    printf "\n"
}

# extract options and their arguments into variables
while true ; do
    case "$1" in
        --openocd-path )
            OPENOCD_PATH="$2"
            shift 2
        ;;
        --openocd-if-cfg )
            OPENOCD_INTERACE_CFG="$2"
            shift 2
        ;;
        -- )
            shift
            break
        ;;
        -h | --help | *)
            usage
            exit 0
        ;;
    esac
done

# arg checks
if [ -z "$OPENOCD_PATH" ] ; then
    printf "\nERROR: OPENOCD_PATH is not defined!\n"
    usage
    exit 1
fi

if [ -z "$OPENOCD_INTERACE_CFG" ] ; then
    printf "\nERROR: OPENOCD_INTERACE_CFG is not defined!\n"
    usage
    exit 1
fi


# confirmation print
printf "\n"
printf "OPENOCD_PATH=$OPENOCD_PATH\n"
printf "OPENOCD_INTERACE_CFG=$OPENOCD_INTERACE_CFG\n"
printf "\n"
################################################################################



PROJECT_ROOT_DIR=$(cd .. ; printf %s "$PWD")
PROJECT_RTL_DIR="${PROJECT_ROOT_DIR}/fpga/rtl"

# the generated .openocd script only focusses on loading the design and setting the IOMUX
#  registers for the design - it does not do anything related to initialization of the EOS_S3
# typically, we need to ensure that the EOS_S3 has been reset before loading the design.

# also, the script is generated with the expectation that it will be run from the gdb interface
# so the target is already defined while running, for example, the 'mww' commands.
# To run this directly, the target must be specified - in our case, the target is 'eos_s3.cpu', as 
# defined in the scripts/targets/eos_s3.cfg in openocd 

# we will customize a new openocd script on the fly and then use it.
# we can add steps BEFORE and AFTER the load-fpga-design script
# we will also add the '_TARGETNAME' in front of all commands that need it.

CUSTOM_OPENOCD_SCRIPT="custom_eoss3.openocd"
CUSTOM_OPENOCD_SCRIPT_LOG="custom_eoss3.openocd.log"

# write "NOTHING" into file, i.e. reset the contents, faster than delete + touch.
#https://askubuntu.com/a/549672
: > "$CUSTOM_OPENOCD_SCRIPT"

# BEFORE
echo "init" >> "$CUSTOM_OPENOCD_SCRIPT"
echo "reset halt" >> "$CUSTOM_OPENOCD_SCRIPT"
echo 'echo "_CHIPNAME=$_CHIPNAME"' >> "$CUSTOM_OPENOCD_SCRIPT"
echo 'echo "_TARGETNAME=$_TARGETNAME"' >> "$CUSTOM_OPENOCD_SCRIPT"
echo 'echo "_CPUTAPID=$_CPUTAPID"' >> "$CUSTOM_OPENOCD_SCRIPT"
echo ""  >> "$CUSTOM_OPENOCD_SCRIPT"
echo ""  >> "$CUSTOM_OPENOCD_SCRIPT"


# fpga-design (replace 'mww' with 'eos_s3.cpu mww') : TODO come back to make it more generic.
REPLACE_FROM="mww"
REPLACE_TO="eos_s3.cpu mww"
# https://stackoverflow.com/a/1521498/3379867
while IFS="" read -r FILE_LINE || [ -n "$FILE_LINE" ] ; do

    #echo ""
    #echo "$FILE_LINE"
    # ref: https://stackoverflow.com/a/55131165
    FILE_LINE=${FILE_LINE/$REPLACE_FROM/$REPLACE_TO}
    #echo "$FILE_LINE"
    #echo ""

    echo "$FILE_LINE" >> "$CUSTOM_OPENOCD_SCRIPT"

done < "$PROJECT_RTL_DIR"/*.openocd


# AFTER
echo "" >> "$CUSTOM_OPENOCD_SCRIPT"
echo "" >> "$CUSTOM_OPENOCD_SCRIPT"
# the JIM-TCL proc is called load_bitstream in the generated openocd script, invoke it
echo "load_bitstream" >> "$CUSTOM_OPENOCD_SCRIPT"
echo "eos_s3.cpu mdw 0x40005484" >> "$CUSTOM_OPENOCD_SCRIPT"
echo "shutdown" >> "$CUSTOM_OPENOCD_SCRIPT"


# run the custom script now
"$OPENOCD_PATH" -f "$OPENOCD_INTERACE_CFG" -f target/eos_s3.cfg -f "${PWD}/${CUSTOM_OPENOCD_SCRIPT}" 2>&1 | tee "$CUSTOM_OPENOCD_SCRIPT_LOG"


# remove the custom script/log (disable for debugging the script)
rm "$CUSTOM_OPENOCD_SCRIPT"
rm "$CUSTOM_OPENOCD_SCRIPT_LOG"
