#!/bin/bash

################ DO NOT USE YET ###################

# customize loading the fpga design (.openocd) with BEFORE and AFTER steps as needed,
# REQ:
# 1. OpenOCD probe is connected to EOS_S3 and it is in DEBUG mode
# 2. openocd is available in the path ('source debugenvsetup.sh')
# 3. (.openocd) has been generated by adding a 'openocd' to the -dump command to ql_symbiflow

# fallback to assuming it is on the path
OPENOCDEXE="openocd"
GDBEXE="arm-none-eabi-gdb"

# if arguments is passed to this script, then it must to path to openocd + gdb
# $1 == path to openocd
# $2 == path to gdb
if [ $# == 2 ] ; then
    OPENOCDEXE="$1"
    GDBEXE="$2"
fi

# the generated .openocd script only focusses on loading the design and setting the IOMUX
#  registers for the design - it does not do anything related to initialization of the EOS_S3
# typically, we need to ensure that the EOS_S3 has been reset before loading the design.

# run openocd (background)
OPENOCD_FPGA_DESIGN_SCRIPT=$(ls ${PWD}/fpga/rtl/*.openocd)
#echo "$OPENOCD_FPGA_DESIGN_SCRIPT"

"$OPENOCDEXE" -f interface/jlink_swd.cfg -f target/eos_s3.cfg -f "${OPENOCD_FPGA_DESIGN_SCRIPT}" &

# run gdb
"$GDBEXE" -batch -ex "target remote localhost:3333" -ex "monitor init" -ex "monitor reset halt" -ex "monitor mdw 0x40005484" -ex "shutdown"
