/*
 * ql_SensorHub_MemoryMap.h
 *
 *  Created on: 06-Aug-2017
 *      Author: AKKumar
 */

#ifndef APP_SHUB_INC_QL_SENSORHUB_MEMORYMAP_H_
#define APP_SHUB_INC_QL_SENSORHUB_MEMORYMAP_H_

#include <Fw_global_config.h>

#define SENSORHUB_MEMORYMAP_BASE_ADDR				0x2007C000


/* SECTION 1: LIVE SENSOR DATA */
#define LIVE_SENSOR_DATA_SECTION_ADDR				(SENSORHUB_MEMORYMAP_BASE_ADDR)

#define LIVE_SENSOR_DATA_PACKET_SIZE				(16)

#define LIVE_SENSOR_DATA_ADDR						(LIVE_SENSOR_DATA_SECTION_ADDR)
// BMX160
#define LIVE_SENSOR_DATA_ACCEL_BMX160_ADDR		    (LIVE_SENSOR_DATA_ADDR)
#define LIVE_SENSOR_DATA_MAG_BMX160_ADDR			(LIVE_SENSOR_DATA_ACCEL_BMX160_ADDR + LIVE_SENSOR_DATA_PACKET_SIZE)
#define LIVE_SENSOR_DATA_GYRO_BMX160_ADDR			(LIVE_SENSOR_DATA_MAG_BMX160_ADDR + LIVE_SENSOR_DATA_PACKET_SIZE)
#define LIVE_SENSOR_DATA_TEMP_BMX160_ADDR			(LIVE_SENSOR_DATA_GYRO_BMX160_ADDR + LIVE_SENSOR_DATA_PACKET_SIZE)
// DPS310
#define LIVE_SENSOR_DATA_TEMP0_DPS310_ADDR			(LIVE_SENSOR_DATA_TEMP_BMX160_ADDR + LIVE_SENSOR_DATA_PACKET_SIZE)
#define LIVE_SENSOR_DATA_TEMP1_DPS310_ADDR			(LIVE_SENSOR_DATA_TEMP0_DPS310_ADDR + LIVE_SENSOR_DATA_PACKET_SIZE)
#define LIVE_SENSOR_DATA_PRESS_DPS310_ADDR			(LIVE_SENSOR_DATA_TEMP1_DPS310_ADDR + LIVE_SENSOR_DATA_PACKET_SIZE)
// HX3313
#define LIVE_SENSOR_DATA_HRS_HX3313_ADDR			(LIVE_SENSOR_DATA_PRESS_DPS310_ADDR + LIVE_SENSOR_DATA_PACKET_SIZE)
#define LIVE_SENSOR_DATA_ALS1_HX3313_ADDR			(LIVE_SENSOR_DATA_HRS_HX3313_ADDR + LIVE_SENSOR_DATA_PACKET_SIZE)
#define LIVE_SENSOR_DATA_ALS2_HX3313_ADDR			(LIVE_SENSOR_DATA_ALS1_HX3313_ADDR + LIVE_SENSOR_DATA_PACKET_SIZE)
#define LIVE_SENSOR_DATA_PS_HX3313_ADDR			    (LIVE_SENSOR_DATA_ALS2_HX3313_ADDR + LIVE_SENSOR_DATA_PACKET_SIZE)
// BMA400
#define LIVE_SENSOR_DATA_ACCEL_BMA400_ADDR			(LIVE_SENSOR_DATA_PS_HX3313_ADDR + LIVE_SENSOR_DATA_PACKET_SIZE)
#define LIVE_SENSOR_DATA_STEP_BMA400_ADDR			(LIVE_SENSOR_DATA_ACCEL_BMA400_ADDR + LIVE_SENSOR_DATA_PACKET_SIZE)
#define LIVE_SENSOR_DATA_TAP_BMA400_ADDR			(LIVE_SENSOR_DATA_STEP_BMA400_ADDR + LIVE_SENSOR_DATA_PACKET_SIZE)
#define LIVE_SENSOR_DATA_CUSTOM1_BMA400_ADDR	    (LIVE_SENSOR_DATA_TAP_BMA400_ADDR + LIVE_SENSOR_DATA_PACKET_SIZE)
#define LIVE_SENSOR_DATA_CUSTOM2_BMA400_ADDR        (LIVE_SENSOR_DATA_CUSTOM1_BMA400_ADDR + LIVE_SENSOR_DATA_PACKET_SIZE)

#define LIVE_SENSOR_DATA_SECTION_SIZE				(16*LIVE_SENSOR_DATA_PACKET_SIZE)


   
// not used for now:
/* SECTION 2: BATCH BUFFER INFO FOR SENSOR */
#define BATCH_BUFFER_INFO_SECTION_ADDR				(LIVE_SENSOR_DATA_SECTION_ADDR + LIVE_SENSOR_DATA_SECTION_SIZE)

#define BATCH_BUFFER_INFO_ADDR						(BATCH_BUFFER_INFO_SECTION_ADDR)
#define BATCH_BUFFER_INFO_SIZE						(8)


#define BATCH_BUFFER_INFO_ADDR_ACCEL				(BATCH_BUFFER_INFO_ADDR)
#define BATCH_BUFFER_INFO_ADDR_ACCEL2				(BATCH_BUFFER_INFO_ADDR_ACCEL + BATCH_BUFFER_INFO_SIZE)
#define BATCH_BUFFER_INFO_ADDR_MAG					(BATCH_BUFFER_INFO_ADDR_ACCEL2 + BATCH_BUFFER_INFO_SIZE)
#define BATCH_BUFFER_INFO_ADDR_GYRO					(BATCH_BUFFER_INFO_ADDR_MAG + BATCH_BUFFER_INFO_SIZE)

#define BATCH_BUFFER_INFO_SECTION_SIZE				(4*BATCH_BUFFER_INFO_SIZE) // support 4 sensors.


/* SECTION 3: BATCH BUFFER DATA FOR SENSOR */
/* we have enough memory for only 3 batch buffers together at any point of time */
#define BATCH_BUFFER_DATA_SECTION_ADDR				(BATCH_BUFFER_INFO_SECTION_ADDR + BATCH_BUFFER_INFO_SECTION_SIZE)

#define BATCH_BUFFER_DATA_ADDR_BUFFER1				(BATCH_BUFFER_DATA_SECTION_ADDR)
#define BATCH_BUFFER_DATA_SIZE_BUFFER1				(12*400*1) // 12B packet * 800 packets/second * 1 second MAX.


#define BATCH_BUFFER_DATA_ADDR_BUFFER2				(BATCH_BUFFER_DATA_ADDR_BUFFER1 + BATCH_BUFFER_DATA_SIZE_BUFFER1)
#define BATCH_BUFFER_DATA_SIZE_BUFFER2				(12*400*1) // 12B packet * 800 packets/second * 1 second MAX.


#define BATCH_BUFFER_DATA_ADDR_BUFFER3				(BATCH_BUFFER_DATA_ADDR_BUFFER2 + BATCH_BUFFER_DATA_SIZE_BUFFER2)
#define BATCH_BUFFER_DATA_SIZE_BUFFER3				(12*400*1) // 12B packet * 800 packets/second * 1 second MAX.

#define BATCH_BUFFER_DATA_SECTION_SIZE				(BATCH_BUFFER_DATA_SIZE_BUFFER1 + BATCH_BUFFER_DATA_SIZE_BUFFER2 + BATCH_BUFFER_DATA_SIZE_BUFFER3)


#endif /* APP_SHUB_INC_QL_SENSORHUB_MEMORYMAP_H_ */
